import Link from "next/link";
import Head from "next/head";

const About = () => {
  return (
    <div>
      <Head>
        <title>About NorDev</title>
        <meta
          name="NorDev is a Frontend Web Development and UI/UX design agency. We
          create websites that will bring value to your business."
          content="Generated by create next app"
        />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="about">
        <div className="line"></div>
        <div className="abt-heading">About NorDev</div>

        <div className="big-heading">Frontend Web Developer</div>

        <div className="small-heading">
          Professional Web, Ui/Ux Design
          <span>Brand First&#8482; – Brand Strategy to Captivate.</span>
        </div>

        <p className="first">
          NorDev is a Frontend Web Development and UI/UX design agency. We
          create websites that will bring value to your business.
        </p>
        <p className="second">
          Our mission is to realize the valuable, distinguishable brand that
          exists within every one of our clients, and to captivate the market
          with that brand. Our brand consultant works with you to evaluate your
          core message. Then we innovate your current brand to captivate your
          target market. Let us help you to create the website of your dreams
          and assist you in growing your business using our experience. Please
          contact us so that we can discuss your needs soon.
        </p>

        <div className="more-details">
          <Link href="/work">let's talk!</Link>
        </div>
      </div>
    </div>
  );
};

export default About;
