import React from "react";
import { AiOutlineHtml5 } from "react-icons/ai";
import { DiCss3Full } from "react-icons/di";
import { SiJavascript } from "react-icons/si";
import { FaSass } from "react-icons/fa";
import { FiFigma } from "react-icons/fi";
import { RiFlutterFill } from "react-icons/ri";
import { FaLaravel } from "react-icons/fa";
import { SiMysql } from "react-icons/si";
import { SiMongodb } from "react-icons/si";
import { DiReact } from "react-icons/di";
import { BsDash } from "react-icons/bs";
import Head from "next/head";

const services = () => {
  return (
    <div className="sevices">
      <Head>
        <title>Services</title>
        <meta
          name="Nor Art is a digital art platform that connects art enthusiasts,
          galleries from countries around the world."
          content="Generated by create next app"
        />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="intro-heading">
        <h1>Turning great ideas into unique experiences.</h1>
        <div className="container">
          <p>
            norDev is a design agency tailored for ambitious companies in rapid
            growth or major change. We're here for those who challenge
            coventions and push for better. Through brand strategy, identity
            development, and product design we help our clients shape what's
            next.
          </p>
          {/* <p>
            Advance in technology let us make more useful products. But it's
            first when they connect with us emotionally they have the power to
            become loved digital experiences. Working with brands and products
            as one, we tear down the wall separating heart and mind.
          </p> */}
          <p>
            Designed to travel light and move fast, we help our customers push
            forward. In other words, we know how to serve your early-stage needs
            and simultaneously build the foundation of a great brand.
          </p>

          <p>Contact us today.</p>
        </div>
        <div className="framework-container">
          <AiOutlineHtml5 className="icon" />
          <DiCss3Full className="icon" />
          <SiJavascript className="icon" />
          <FaSass className="icon" />
          <FiFigma className="icon" />
          <RiFlutterFill className="icon" />
          <DiReact className="icon" />
          <FaLaravel className="icon" />
          <SiMongodb className="icon" />
          <SiMysql className="icon" />
        </div>

        <div className="real-services">
          <h1>We can help you with</h1>
          <div className="container">
            <p>
              <BsDash className="icon" />
              Advice on your business concept
            </p>
            <p>
              <BsDash className="icon" />
              Describe and position your company
            </p>
            <p>
              <BsDash className="icon" />
              Name your next venture
            </p>
            <p>
              <BsDash className="icon" />
              Develop your unique brand identity
            </p>
            <p>
              <BsDash className="icon" />
              Activate your brand through conten
            </p>
          </div>
        </div>

        <p className="center-paragraph">
          We focus on what do best, and for all other matters we've developed a
          high quality network of partners. We'll make sure it all fits.
        </p>
      </div>
    </div>
  );
};

export default services;
